name: Test-pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install civo
      uses: civo/action-civo@v1.0.0
      with:
        token: ${{ secrets.CIVO_TOKEN }}

    - name: Creating cluster
      run: civo kubernetes create kube_demo --size=g3.k3s.extrasmall --nodes=2 --wait
